//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Codes_Status
    {
        public Codes_Status()
        {
            this.Credential = new HashSet<Credential>();
            this.Organization = new HashSet<Organization>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
    
        public virtual ICollection<Credential> Credential { get; set; }
        public virtual ICollection<Organization> Organization { get; set; }
    }
}
