//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Codes_Countries
    {
        public Codes_Countries()
        {
            this.Entity_Address = new HashSet<Entity_Address>();
            this.Organization_Address = new HashSet<Organization_Address>();
        }
    
        public int Id { get; set; }
        public int CountryNumber { get; set; }
        public string CommonName { get; set; }
        public string FormalName { get; set; }
        public string Type { get; set; }
        public string SubType { get; set; }
        public string Sovereignty { get; set; }
        public string Capital { get; set; }
        public string CurrencyCode { get; set; }
        public string CurrencyName { get; set; }
        public string CommonCurrencyName { get; set; }
        public Nullable<double> TelephoneCode { get; set; }
        public string TwoLetterCode { get; set; }
        public string ThreeLetterCode { get; set; }
        public string IANACountryCodeTLD { get; set; }
        public bool IsActive { get; set; }
        public int SortOrder { get; set; }
    
        public virtual ICollection<Entity_Address> Entity_Address { get; set; }
        public virtual ICollection<Organization_Address> Organization_Address { get; set; }
    }
}
