//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Codes_PropertyCategory
    {
        public Codes_PropertyCategory()
        {
            this.Codes_PropertyValue = new HashSet<Codes_PropertyValue>();
            this.Entity_FrameworkItem = new HashSet<Entity_FrameworkItem>();
            this.Entity_PropertyOther = new HashSet<Entity_PropertyOther>();
            this.Entity_Reference = new HashSet<Entity_Reference>();
            this.Organization_PropertyOther = new HashSet<Organization_PropertyOther>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int SortOrder { get; set; }
        public bool IsActive { get; set; }
        public string SchemaName { get; set; }
        public string SchemaUrl { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string CodeName { get; set; }
        public Nullable<int> InterfaceType { get; set; }
    
        public virtual ICollection<Codes_PropertyValue> Codes_PropertyValue { get; set; }
        public virtual ICollection<Entity_FrameworkItem> Entity_FrameworkItem { get; set; }
        public virtual ICollection<Entity_PropertyOther> Entity_PropertyOther { get; set; }
        public virtual ICollection<Entity_Reference> Entity_Reference { get; set; }
        public virtual ICollection<Organization_PropertyOther> Organization_PropertyOther { get; set; }
    }
}
