//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Codes_PropertyValue
    {
        public Codes_PropertyValue()
        {
            this.Entity_CostProfileItem = new HashSet<Entity_CostProfileItem>();
            this.Entity_Property = new HashSet<Entity_Property>();
            this.Entity_Reference = new HashSet<Entity_Reference>();
            this.Credential_ConnectionProfile = new HashSet<Credential_ConnectionProfile>();
            this.Entity_ConditionProfile = new HashSet<Entity_ConditionProfile>();
        }
    
        public int Id { get; set; }
        public int CategoryId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string SchemaName { get; set; }
        public string SchemaUrl { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<int> Totals { get; set; }
        public Nullable<bool> IsSubType1 { get; set; }
    
        public virtual Codes_PropertyCategory Codes_PropertyCategory { get; set; }
        public virtual ICollection<Entity_CostProfileItem> Entity_CostProfileItem { get; set; }
        public virtual ICollection<Entity_Property> Entity_Property { get; set; }
        public virtual ICollection<Entity_Reference> Entity_Reference { get; set; }
        public virtual ICollection<Credential_ConnectionProfile> Credential_ConnectionProfile { get; set; }
        public virtual ICollection<Entity_ConditionProfile> Entity_ConditionProfile { get; set; }
    }
}
