//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Tables
{
    using System;
    using System.Collections.Generic;
    
    public partial class Codes_CredentialAgentRelationship
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Codes_CredentialAgentRelationship()
        {
            this.Credential_AgentRelationship = new HashSet<Credential_AgentRelationship>();
            this.Entity_AgentRelationship = new HashSet<Entity_AgentRelationship>();
            this.Entity_QA_Action = new HashSet<Entity_QA_Action>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string SchemaTag { get; set; }
        public string ReverseRelation { get; set; }
        public string ReverseSchemaTag { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsQARole { get; set; }
        public Nullable<bool> IsAgentToAgentRole { get; set; }
        public Nullable<bool> IsEntityToAgentRole { get; set; }
        public Nullable<bool> IsAssessmentAgentRole { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Credential_AgentRelationship> Credential_AgentRelationship { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entity_AgentRelationship> Entity_AgentRelationship { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entity_QA_Action> Entity_QA_Action { get; set; }
    }
}
