//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Tables
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credential
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Credential()
        {
            this.Credential_AgentRelationship = new HashSet<Credential_AgentRelationship>();
            this.Credential_AgentRelationship1 = new HashSet<Credential_AgentRelationship>();
            this.Credential_ConnectionProfile = new HashSet<Credential_ConnectionProfile>();
            this.Credential_FrameworkItem = new HashSet<Credential_FrameworkItem>();
            this.Credential_Property = new HashSet<Credential_Property>();
            this.Credential_PropertyOther = new HashSet<Credential_PropertyOther>();
            this.Credential_TimeToEarn = new HashSet<Credential_TimeToEarn>();
            this.Entity_Credential = new HashSet<Entity_Credential>();
            this.Entity_QA_Action = new HashSet<Entity_QA_Action>();
            this.Entity_VerificationProfile = new HashSet<Entity_VerificationProfile>();
        }
    
        public int Id { get; set; }
        public System.Guid RowId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Version { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public string Url { get; set; }
        public string LatestVersionUrl { get; set; }
        public string ReplacesVersionUrl { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<int> LastUpdatedById { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string CredentialRegistryId { get; set; }
        public Nullable<int> ManagingOrgId { get; set; }
        public string AlternateName { get; set; }
        public string CTID { get; set; }
    
        public virtual Codes_Status Codes_Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Credential_AgentRelationship> Credential_AgentRelationship { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Credential_AgentRelationship> Credential_AgentRelationship1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Credential_ConnectionProfile> Credential_ConnectionProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Credential_FrameworkItem> Credential_FrameworkItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Credential_Property> Credential_Property { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Credential_PropertyOther> Credential_PropertyOther { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Credential_TimeToEarn> Credential_TimeToEarn { get; set; }
        public virtual Organization Organization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entity_Credential> Entity_Credential { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entity_QA_Action> Entity_QA_Action { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entity_VerificationProfile> Entity_VerificationProfile { get; set; }
    }
}
