//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Tables
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CTITables : DbContext
    {
		public CTITables()
            : base("name=CTIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Codes_CredentialAgentRelationship> Codes_CredentialAgentRelationship { get; set; }
        public virtual DbSet<Codes_PropertyCategory> Codes_PropertyCategory { get; set; }
        public virtual DbSet<Codes_PropertyValue> Codes_PropertyValue { get; set; }
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<ActivityLog> ActivityLogs { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUserRole> AspNetUserRoles { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Assessment> Assessments { get; set; }
        public virtual DbSet<CIPCode2010> CIPCode2010 { get; set; }
        public virtual DbSet<Codes_Countries> Codes_Countries { get; set; }
        public virtual DbSet<Codes_Currency> Codes_Currency { get; set; }
        public virtual DbSet<Codes_EntityType> Codes_EntityType { get; set; }
        public virtual DbSet<Codes_Status> Codes_Status { get; set; }
        public virtual DbSet<ConnectionProfile_Assessment> ConnectionProfile_Assessment { get; set; }
        public virtual DbSet<ConnectionProfile_Property> ConnectionProfile_Property { get; set; }
        public virtual DbSet<Credential> Credentials { get; set; }
        public virtual DbSet<Credential_AgentRelationship> Credential_AgentRelationship { get; set; }
        public virtual DbSet<Credential_ConnectionProfile> Credential_ConnectionProfile { get; set; }
        public virtual DbSet<Credential_FrameworkItem> Credential_FrameworkItem { get; set; }
        public virtual DbSet<Credential_Property> Credential_Property { get; set; }
        public virtual DbSet<Credential_PropertyOther> Credential_PropertyOther { get; set; }
        public virtual DbSet<Credential_TimeToEarn> Credential_TimeToEarn { get; set; }
        public virtual DbSet<Entity> Entities { get; set; }
        public virtual DbSet<Entity_AgentRelationship> Entity_AgentRelationship { get; set; }
        public virtual DbSet<Entity_Assessment> Entity_Assessment { get; set; }
        public virtual DbSet<Entity_Competency> Entity_Competency { get; set; }
        public virtual DbSet<Entity_CostProfile> Entity_CostProfile { get; set; }
        public virtual DbSet<Entity_CostProfileItem> Entity_CostProfileItem { get; set; }
        public virtual DbSet<Entity_Credential> Entity_Credential { get; set; }
        public virtual DbSet<Entity_DurationProfile> Entity_DurationProfile { get; set; }
        public virtual DbSet<Entity_FrameworkItem> Entity_FrameworkItem { get; set; }
        public virtual DbSet<Entity_LearningOpportunity> Entity_LearningOpportunity { get; set; }
        public virtual DbSet<Entity_Property> Entity_Property { get; set; }
        public virtual DbSet<Entity_PropertyOther> Entity_PropertyOther { get; set; }
        public virtual DbSet<Entity_QA_Action> Entity_QA_Action { get; set; }
        public virtual DbSet<Entity_Reference> Entity_Reference { get; set; }
        public virtual DbSet<Entity_RevocationProfile> Entity_RevocationProfile { get; set; }
        public virtual DbSet<Entity_TaskProfile> Entity_TaskProfile { get; set; }
        public virtual DbSet<Entity_VerificationProfile> Entity_VerificationProfile { get; set; }
        public virtual DbSet<GeoCoordinate> GeoCoordinates { get; set; }
        public virtual DbSet<JurisdictionProfile> JurisdictionProfiles { get; set; }
        public virtual DbSet<LearningOpportunity> LearningOpportunities { get; set; }
        public virtual DbSet<NAIC> NAICS { get; set; }
        public virtual DbSet<ONET_SOC> ONET_SOC { get; set; }
        public virtual DbSet<ONET_SOC_JobFamily> ONET_SOC_JobFamily { get; set; }
        public virtual DbSet<Organization> Organizations { get; set; }
        public virtual DbSet<Organization_Address> Organization_Address { get; set; }
        public virtual DbSet<Organization_Member> Organization_Member { get; set; }
        public virtual DbSet<Organization_Property> Organization_Property { get; set; }
        public virtual DbSet<Organization_PropertyOther> Organization_PropertyOther { get; set; }
        public virtual DbSet<Organization_Service> Organization_Service { get; set; }
        public virtual DbSet<Person> People { get; set; }
    }
}
