//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConditionProfile_ParentSummary
    {
        public int ParentBaseId { get; set; }
        public System.Guid ParentRowId { get; set; }
        public string ParentName { get; set; }
        public string ParentDescription { get; set; }
        public string ParentUrl { get; set; }
        public int ParentEntityTypeId { get; set; }
        public int parentEntityId { get; set; }
        public string Name { get; set; }
        public int EntityId { get; set; }
        public System.Guid EntityUid { get; set; }
        public int EntityConditionProfileId { get; set; }
        public int ConnectionTypeId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public System.Guid RowId { get; set; }
        public string ParentEntityType { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
    }
}
