//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credential_AgentRoleIdCSV
    {
        public int CredentialId { get; set; }
        public int OrgId { get; set; }
        public System.Guid AgentUid { get; set; }
        public string Name { get; set; }
        public string RoleIds { get; set; }
    }
}
