//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credential_Summary
    {
        public int Id { get; set; }
        public System.Guid EntityUid { get; set; }
        public string Name { get; set; }
        public string CredentialType { get; set; }
        public string CredentialTypeSchema { get; set; }
        public string Description { get; set; }
        public string RelationshipType { get; set; }
        public int OrgId { get; set; }
        public string OrganizationName { get; set; }
        public int owingOrgId { get; set; }
        public string owingOrganization { get; set; }
        public Nullable<int> ManagingOrgId { get; set; }
        public string ManagingOrganization { get; set; }
        public string Url { get; set; }
        public string Version { get; set; }
        public string LatestVersionUrl { get; set; }
        public string ReplacesVersionUrl { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public int CreatedById { get; set; }
        public int LastUpdatedById { get; set; }
        public Nullable<int> CredentialTypeId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string CTID { get; set; }
        public string CredentialRegistryId { get; set; }
        public string availableOnlineAt { get; set; }
    }
}
