//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entity_AssertionCSV
    {
        public int EntityId { get; set; }
        public System.Guid AgentUid { get; set; }
        public int OrgId { get; set; }
        public string Organization { get; set; }
        public int TargetEntityTypeId { get; set; }
        public string TargetEntityType { get; set; }
        public System.Guid TargetEntityUid { get; set; }
        public Nullable<int> TargetEntityBaseId { get; set; }
        public string TargetEntityName { get; set; }
        public string TargetEntityDescription { get; set; }
        public string TargetEntitySubjectWebpage { get; set; }
        public string TargetEntityImageUrl { get; set; }
        public string TargetCTID { get; set; }
        public string CtdlType { get; set; }
        public string RoleIds { get; set; }
        public string Roles { get; set; }
    }
}
