//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entity_FrameworkItems_Totals
    {
        public int EntityTypeId { get; set; }
        public int CategoryId { get; set; }
        public Nullable<int> CodeId { get; set; }
        public string Title { get; set; }
        public string FrameworkCode { get; set; }
        public Nullable<int> TOTALS { get; set; }
    }
}
