//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entity_Assertion_Summary
    {
        public int EntityAssertionId { get; set; }
        public System.Guid AgentUid { get; set; }
        public string Organization { get; set; }
        public int OrgId { get; set; }
        public string AgentDescription { get; set; }
        public string AgentSubjectWebpage { get; set; }
        public string AgentImageUrl { get; set; }
        public string AgentCTID { get; set; }
        public int EntityId { get; set; }
        public int TargetEntityTypeId { get; set; }
        public System.Guid TargetEntityUid { get; set; }
        public string TargetEntityType { get; set; }
        public Nullable<int> TargetEntityBaseId { get; set; }
        public string TargetEntityName { get; set; }
        public string TargetEntityDescription { get; set; }
        public string TargetEntitySubjectWebpage { get; set; }
        public string TargetEntityImageUrl { get; set; }
        public string CtdlType { get; set; }
        public string TargetCTID { get; set; }
        public int AssertionTypeId { get; set; }
        public string AgentToTargetRelationship { get; set; }
        public string TargetToAgentRelationship { get; set; }
        public string RelationshipDescription { get; set; }
        public string SchemaTag { get; set; }
        public string ReverseSchemaTag { get; set; }
        public Nullable<bool> IsQARole { get; set; }
        public Nullable<bool> IsOwnerAgentRole { get; set; }
        public System.DateTime Created { get; set; }
        public int CreatedById { get; set; }
    }
}
