//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entity_FrameworkIndustryGroupSummary
    {
        public int EntityTypeId { get; set; }
        public short CodeGroup { get; set; }
        public string FrameworkGroupTitle { get; set; }
        public Nullable<int> groupCount { get; set; }
    }
}
