//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entity_FrameworkIndustryCodeSummary
    {
        public Nullable<short> CodeGroup { get; set; }
        public string NaicsCode { get; set; }
        public int EntityTypeId { get; set; }
        public string NaicsTitle { get; set; }
        public Nullable<int> Totals { get; set; }
        public Nullable<int> Id { get; set; }
        public string URL { get; set; }
    }
}
