//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entity_PropertyOtherSummary
    {
        public int Id { get; set; }
        public Nullable<int> parentEntityId { get; set; }
        public string parentEntityType { get; set; }
        public int EntityId { get; set; }
        public string EntityType { get; set; }
        public string EntityName { get; set; }
        public Nullable<int> BaseId { get; set; }
        public System.Guid EntityUid { get; set; }
        public int CategoryId { get; set; }
        public string Category { get; set; }
        public string OtherValue { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<int> CreatedById { get; set; }
    }
}
