//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entity_Competencies_ForExport
    {
        public int Id { get; set; }
        public string EntityType { get; set; }
        public int EntityTypeId { get; set; }
        public int BaseId { get; set; }
        public string ParentEntityName { get; set; }
        public Nullable<int> OwningOrgId { get; set; }
        public string OwningOrganization { get; set; }
        public Nullable<System.Guid> orgUid { get; set; }
        public Nullable<int> orgId { get; set; }
        public string OrganizationCtid { get; set; }
        public int CompetencyFrameworkId { get; set; }
        public System.Guid FrameworkUid { get; set; }
        public Nullable<int> NumberOfFrameworks { get; set; }
        public string RecommendedFrameworkName { get; set; }
        public string EducationalFrameworkName { get; set; }
        public string FrameworkCtid { get; set; }
        public string EducationalFrameworkUrl { get; set; }
        public string AlignmentType { get; set; }
        public int ItemId { get; set; }
        public string Competency { get; set; }
        public string Description { get; set; }
        public string TargetName { get; set; }
        public string TargetDescription { get; set; }
        public string TargetUrl { get; set; }
        public string CodedNotation { get; set; }
        public string CompetencyCtid { get; set; }
        public System.Guid CompetencyUid { get; set; }
        public Nullable<System.DateTime> CompetencyCreated { get; set; }
    }
}
