//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entity_Summary
    {
        public int Id { get; set; }
        public int EntityTypeId { get; set; }
        public string EntityType { get; set; }
        public System.Guid EntityUid { get; set; }
        public int parentEntityId { get; set; }
        public Nullable<System.Guid> parentEntityUid { get; set; }
        public string parentEntityType { get; set; }
        public int parentEntityTypeId { get; set; }
        public int BaseId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<int> LastUpdatedById { get; set; }
        public string Url { get; set; }
        public string ImageUrl { get; set; }
        public string CTID { get; set; }
        public Nullable<int> OwningOrgId { get; set; }
        public string OwningOrganization { get; set; }
        public string IsPublished { get; set; }
        public string HasApproval { get; set; }
    }
}
