//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class JurisdictionProfile_Summary
    {
        public int Id { get; set; }
        public string EntityType { get; set; }
        public int BaseId { get; set; }
        public string Name { get; set; }
        public int JurisdictionProfileId { get; set; }
        public System.Guid ParentId { get; set; }
        public Nullable<int> ParentTypeId { get; set; }
        public string JurisdictionName { get; set; }
        public Nullable<int> GeoNamesId { get; set; }
        public Nullable<bool> IsException { get; set; }
        public string GeoCoordinateName { get; set; }
        public string AddressRegion { get; set; }
        public string Country { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public string Url { get; set; }
    }
}
