//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class Naics_Select2DigitCodes
    {
        public string NaicsCode { get; set; }
        public string NaicsTitle { get; set; }
        public string NaicsTitleOnly { get; set; }
    }
}
