//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization_ServiceSummary
    {
        public int OrgServiceId { get; set; }
        public int OrganizationId { get; set; }
        public int CodeId { get; set; }
        public string Organization { get; set; }
        public string Service { get; set; }
        public string Description { get; set; }
        public string SchemaTag { get; set; }
        public Nullable<bool> IsCredentialingService { get; set; }
        public Nullable<bool> IsQAService { get; set; }
        public Nullable<System.DateTime> ServiceCreated { get; set; }
        public Nullable<int> ServiceCreatedById { get; set; }
    }
}
