//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizationProperty_Summary
    {
        public int Id { get; set; }
        public int OrganizationId { get; set; }
        public System.Guid OrgRowId { get; set; }
        public int PropertyValueId { get; set; }
        public string Organization { get; set; }
        public int CategoryId { get; set; }
        public string Category { get; set; }
        public string CategorySchemaName { get; set; }
        public string CategorySchemaUrl { get; set; }
        public string Property { get; set; }
        public string PropertySchemaName { get; set; }
        public string PropertySchemaUrl { get; set; }
        public string OtherValue { get; set; }
        public Nullable<System.DateTime> PropertyCreated { get; set; }
        public Nullable<int> PropertyCreatedById { get; set; }
    }
}
