//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class CredentialAgentRelationships_Summary
    {
        public int CredentialAgentRelationshipId { get; set; }
        public int CredentialId { get; set; }
        public string CredentialName { get; set; }
        public System.Guid ParentUid { get; set; }
        public int RelationshipTypeId { get; set; }
        public string RelationshipType { get; set; }
        public string RelationshipTypeSchema { get; set; }
        public System.Guid AgentUid { get; set; }
        public int OrgId { get; set; }
        public string OrganizationName { get; set; }
        public string ReverseRelation { get; set; }
        public string ReverseSchemaTag { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<int> LastUpdatedById { get; set; }
        public string LastUpdatedBy { get; set; }
    }
}
