//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entity_QAAction_Summary
    {
        public int EntityQAActionId { get; set; }
        public int EntityId { get; set; }
        public System.Guid EntityUid { get; set; }
        public int EntityTypeId { get; set; }
        public string EntityType { get; set; }
        public int RelationshipTypeId { get; set; }
        public string Relationship { get; set; }
        public string ReverseRelation { get; set; }
        public System.Guid AgentUid { get; set; }
        public int AgentEntityId { get; set; }
        public int AgentTypeId { get; set; }
        public string AgentType { get; set; }
        public string AgentName { get; set; }
        public int AgentRelativeId { get; set; }
        public int IssuedCredentialId { get; set; }
        public string CredentialName { get; set; }
        public System.Guid CredentialRowId { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<int> LastUpdatedById { get; set; }
        public System.Guid RowId { get; set; }
        public string RelationshipSchema { get; set; }
        public string ReverseRelationSchema { get; set; }
    }
}
