//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUser_Import
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> OrgId { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<bool> IsImported { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> DefaultRoleId { get; set; }
        public string InitialPassword { get; set; }
    }
}
