//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assessment
    {
        public Assessment()
        {
            this.Entity_Assessment = new HashSet<Entity_Assessment>();
        }
    
        public int Id { get; set; }
        public System.Guid RowId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateEffective { get; set; }
        public string AssessmentExampleUrl { get; set; }
        public Nullable<int> OrgId { get; set; }
        public Nullable<System.Guid> AgentUid { get; set; }
        public string Url { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<int> LastUpdatedById { get; set; }
        public string OtherAssessmentType { get; set; }
        public string IdentificationCode { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> ManagingOrgId { get; set; }
        public string AvailableOnlineAt { get; set; }
    
        public virtual Organization Organization { get; set; }
        public virtual ICollection<Entity_Assessment> Entity_Assessment { get; set; }
    }
}
