//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Codes_Language
    {
        public Codes_Language()
        {
            this.Credential = new HashSet<Credential>();
            this.Assessment = new HashSet<Assessment>();
            this.LearningOpportunity = new HashSet<LearningOpportunity>();
        }
    
        public int Id { get; set; }
        public string LangugeCode { get; set; }
        public string Code_639_2T { get; set; }
        public string Code_639_2B { get; set; }
        public string LanguageName { get; set; }
        public string NativeName { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<bool> HasSublanguage { get; set; }
    
        public virtual ICollection<Credential> Credential { get; set; }
        public virtual ICollection<Assessment> Assessment { get; set; }
        public virtual ICollection<LearningOpportunity> LearningOpportunity { get; set; }
    }
}
