//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConceptScheme
    {
        public int Id { get; set; }
        public System.Guid RowId { get; set; }
        public int OrgId { get; set; }
        public string ConceptSchemaName { get; set; }
        public string CTID { get; set; }
        public string EditorUri { get; set; }
        public string CredentialRegistryId { get; set; }
        public System.DateTime Created { get; set; }
        public int CreatedById { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public int LastUpdatedById { get; set; }
        public Nullable<System.DateTime> LastApproved { get; set; }
        public Nullable<int> LastApprovedById { get; set; }
        public Nullable<System.DateTime> LastPublished { get; set; }
        public Nullable<int> LastPublishedById { get; set; }
    }
}
