//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConditionManifest
    {
        public ConditionManifest()
        {
            this.Entity_CommonCondition = new HashSet<Entity_CommonCondition>();
            this.Entity_ConditionManifest = new HashSet<Entity_ConditionManifest>();
        }
    
        public int Id { get; set; }
        public int OrganizationId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string SubjectWebpage { get; set; }
        public string CTID { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<int> LastUpdatedById { get; set; }
        public System.Guid RowId { get; set; }
        public string CredentialRegistryId { get; set; }
    
        public virtual Organization Organization { get; set; }
        public virtual Account Account { get; set; }
        public virtual Account Account_Modifier { get; set; }
        public virtual ICollection<Entity_CommonCondition> Entity_CommonCondition { get; set; }
        public virtual ICollection<Entity_ConditionManifest> Entity_ConditionManifest { get; set; }
    }
}
