//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostManifest
    {
        public CostManifest()
        {
            this.Entity_CommonCost = new HashSet<Entity_CommonCost>();
            this.Entity_CostManifest = new HashSet<Entity_CostManifest>();
        }
    
        public int Id { get; set; }
        public int OrganizationId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string CostDetails { get; set; }
        public string CTID { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<int> LastUpdatedById { get; set; }
        public System.Guid RowId { get; set; }
        public string CredentialRegistryId { get; set; }
    
        public virtual Organization Organization { get; set; }
        public virtual Account Account_Creator { get; set; }
        public virtual Account Account_Modifier { get; set; }
        public virtual ICollection<Entity_CommonCost> Entity_CommonCost { get; set; }
        public virtual ICollection<Entity_CostManifest> Entity_CostManifest { get; set; }
    }
}
