//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Counts_SiteTotals
    {
        public int Id { get; set; }
        public int CategoryId { get; set; }
        public int EntityTypeId { get; set; }
        public int CodeId { get; set; }
        public string Description { get; set; }
        public Nullable<int> Totals { get; set; }
    }
}
