//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credential_SummaryCache
    {
        public int PK { get; set; }
        public int CredentialId { get; set; }
        public Nullable<int> EntityId { get; set; }
        public string CredentialType { get; set; }
        public string CredentialTypeSchema { get; set; }
        public Nullable<int> CredentialTypeId { get; set; }
        public Nullable<int> IsAQACredential { get; set; }
        public Nullable<int> HasQualityAssurance { get; set; }
        public string CreatorOrgs { get; set; }
        public string OwningOrgs { get; set; }
        public Nullable<int> LearningOppsCompetenciesCount { get; set; }
        public Nullable<int> AssessmentsCompetenciesCount { get; set; }
        public Nullable<int> QARolesCount { get; set; }
        public Nullable<int> HasPartCount { get; set; }
        public Nullable<int> IsPartOfCount { get; set; }
        public Nullable<int> RequiresCount { get; set; }
        public Nullable<int> RecommendsCount { get; set; }
        public Nullable<int> RequiredForCount { get; set; }
        public Nullable<int> IsRecommendedForCount { get; set; }
        public Nullable<int> IsAdvancedStandingForCount { get; set; }
        public Nullable<int> AdvancedStandingFromCount { get; set; }
        public Nullable<int> PreparationForCount { get; set; }
        public Nullable<int> PreparationFromCount { get; set; }
        public Nullable<System.DateTime> LastSyncDate { get; set; }
        public Nullable<System.Guid> OwningAgentUid { get; set; }
        public string QARolesList { get; set; }
        public string QAOrgRolesList { get; set; }
        public string AgentAndRoles { get; set; }
        public Nullable<int> EntryConditionCount { get; set; }
        public Nullable<int> CorequisiteConditionCount { get; set; }
        public Nullable<int> BadgeClaimsCount { get; set; }
    
        public virtual Credential Credential { get; set; }
    }
}
