//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credential_ConnectionProfile
    {
        public int Id { get; set; }
        public int CredentialId { get; set; }
        public int ConnectionTypeId { get; set; }
        public Nullable<System.Guid> AgentUid { get; set; }
        public string Name { get; set; }
        public string Experience { get; set; }
        public Nullable<int> MinimumAge { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateEffective { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<int> LastUpdatedById { get; set; }
        public System.Guid RowId { get; set; }
        public string TargetCredentials { get; set; }
        public string OtherAudienceType { get; set; }
        public string OtherCredentialType { get; set; }
        public Nullable<decimal> YearsOfExperience { get; set; }
    
        public virtual Credential Credential { get; set; }
        public virtual Codes_PropertyValue Codes_PropertyValue { get; set; }
    }
}
