//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CTIViews : DbContext
    {
        public CTIViews()
            : base("name=CTIViews")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Entity_QAAction_Summary> Entity_QAAction_Summary { get; set; }
        public virtual DbSet<Entity_Relationship_AgentSummary> Entity_Relationship_AgentSummary { get; set; }
    }
}
