//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducationFramework_Competency
    {
        public EducationFramework_Competency()
        {
            this.Entity_Competency = new HashSet<Entity_Competency>();
        }
    
        public int Id { get; set; }
        public int EducationFrameworkId { get; set; }
        public string RepositoryUri { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Url { get; set; }
        public string CodedNotation { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public System.Guid RowId { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual EducationFramework EducationFramework { get; set; }
        public virtual ICollection<Entity_Competency> Entity_Competency { get; set; }
    }
}
