//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducationFramework
    {
        public EducationFramework()
        {
            this.EducationFramework_Competency = new HashSet<EducationFramework_Competency>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string FrameworkUrl { get; set; }
        public string RepositoryUri { get; set; }
        public System.Guid RowId { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<int> OwningOrganizationId { get; set; }
        public string CTID { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<int> LastUpdatedById { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ICollection<EducationFramework_Competency> EducationFramework_Competency { get; set; }
    }
}
