//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Import_IdentifierToObjectXref
    {
        public int Id { get; set; }
        public int ParentEntityTypeId { get; set; }
        public int ParentId { get; set; }
        public int InputEntityTypeId { get; set; }
        public string InputIdentifier { get; set; }
        public System.Guid TargetRowId { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<int> CreatedById { get; set; }
    
        public virtual Codes_EntityType Codes_EntityType { get; set; }
    }
}
