//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class JurisdictionProfile
    {
        public System.Guid ParentId { get; set; }
        public Nullable<int> ParentTypeId { get; set; }
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsOnlineJurisdiction { get; set; }
        public Nullable<bool> IsGlobalJurisdiction { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<int> LastUpdatedById { get; set; }
        public System.Guid RowId { get; set; }
        public Nullable<int> JProfilePurposeId { get; set; }
    
        public virtual Codes_EntityType Codes_EntityType { get; set; }
    }
}
