//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NAICS_NaicsGroup
    {
        public NAICS_NaicsGroup()
        {
            this.NAICS = new HashSet<NAICS>();
        }
    
        public short NaicsGroup { get; set; }
        public string NaicsTitle { get; set; }
        public string URL { get; set; }
        public Nullable<int> Totals { get; set; }
    
        public virtual ICollection<NAICS> NAICS { get; set; }
    }
}
