//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ONET_SOC_JobFamily
    {
        public ONET_SOC_JobFamily()
        {
            this.ONET_SOC = new HashSet<ONET_SOC>();
        }
    
        public int JobFamilyId { get; set; }
        public string Description { get; set; }
        public Nullable<int> Totals { get; set; }
    
        public virtual ICollection<ONET_SOC> ONET_SOC { get; set; }
    }
}
