//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization
    {
        public Organization()
        {
            this.Assessment = new HashSet<Assessment>();
            this.Credential = new HashSet<Credential>();
            this.LearningOpportunity = new HashSet<LearningOpportunity>();
            this.Organization_Member = new HashSet<Organization_Member>();
            this.Organization_PropertyOther = new HashSet<Organization_PropertyOther>();
            this.Organization_Service = new HashSet<Organization_Service>();
            this.Organization_VerificationStatus = new HashSet<Organization_VerificationStatus>();
            this.ConditionManifest = new HashSet<ConditionManifest>();
            this.CostManifest = new HashSet<CostManifest>();
        }
    
        public int Id { get; set; }
        public System.Guid RowId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string URL { get; set; }
        public string UniqueURI { get; set; }
        public string ImageURL { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<int> LastUpdatedById { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string Purpose { get; set; }
        public string FoundingDate { get; set; }
        public string CredentialRegistryId { get; set; }
        public string ServiceTypeOther { get; set; }
        public string CTID { get; set; }
        public string AvailabilityListing { get; set; }
        public string Versioning { get; set; }
        public string AgentPurposeUrl { get; set; }
        public string MissionAndGoalsStatement { get; set; }
        public string MissionAndGoalsStatementDescription { get; set; }
        public Nullable<bool> ISQAOrganization { get; set; }
        public string AlternativeIdentifier { get; set; }
        public Nullable<bool> IsThirdPartyOrganization { get; set; }
    
        public virtual ICollection<Assessment> Assessment { get; set; }
        public virtual Codes_Status Codes_Status { get; set; }
        public virtual ICollection<Credential> Credential { get; set; }
        public virtual ICollection<LearningOpportunity> LearningOpportunity { get; set; }
        public virtual ICollection<Organization_Member> Organization_Member { get; set; }
        public virtual ICollection<Organization_PropertyOther> Organization_PropertyOther { get; set; }
        public virtual ICollection<Organization_Service> Organization_Service { get; set; }
        public virtual Account Account_Creator { get; set; }
        public virtual Account Account_Modifier { get; set; }
        public virtual ICollection<Organization_VerificationStatus> Organization_VerificationStatus { get; set; }
        public virtual ICollection<ConditionManifest> ConditionManifest { get; set; }
        public virtual ICollection<CostManifest> CostManifest { get; set; }
    }
}
