//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistryPublishingHistory
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string Environment { get; set; }
        public string DataOwnerCTID { get; set; }
        public string PublishIdentifier { get; set; }
        public string PublishMethodURI { get; set; }
        public string PublishingEntityType { get; set; }
        public string CtdlType { get; set; }
        public string EntityCtid { get; set; }
        public string PublishInput { get; set; }
        public string PublishPayload { get; set; }
        public string EnvelopeId { get; set; }
    }
}
